// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.MarkdownLinkExtractor
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("totalLinks")]
        public long TotalLinks { get; set; }

        [JsonProperty("links")]
        public Link[] Links { get; set; }

        [JsonProperty("categories")]
        public Categories Categories { get; set; }

        [JsonProperty("markdownLength")]
        public long MarkdownLength { get; set; }
    }

    public partial class Categories
    {
        [JsonProperty("internal")]
        public Email Internal { get; set; }

        [JsonProperty("external")]
        public Email External { get; set; }

        [JsonProperty("email")]
        public Email Email { get; set; }

        [JsonProperty("other")]
        public Email Other { get; set; }
    }

    public partial class Email
    {
        [JsonProperty("count")]
        public long Count { get; set; }

        [JsonProperty("links")]
        public Link[] Links { get; set; }
    }

    public partial class Link
    {
        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("reference", NullValueHandling = NullValueHandling.Ignore)]
        public string Reference { get; set; }
    }
}
